### ISSUE TITLE
[Bug/Feature Request?] End Portal remains after breaking Frame blocks, can't remove it in survival

### ISSUE THREAD

**Issue by Abbanon** [PalgamingHD/End-Portal-Creater#1]
As the title implies, I've noticed that once you build an End Portal and break the Frames, the actual End Portal stays behind with no way to destroy it unless you go in Creative.
Would it be possible to make the Portal disappear once you break one of the Frame blocks, similar to Nether Portals?
Or have some other way to manually break the Portal in Survival?

**Comment by PalgamingHD** [comment]
I think that's for the best anyway but if you want to break the portal. If you want to get rid of the portal "The end portal block can currently be broken using TNT"
