### ISSUE TITLE
[Bug Report] The portal frame recipe calls for a diamond instead of the expected dragons egg. (Version 2.0.1)

### ISSUE THREAD

**Issue by LunaEversor** [PalgamingHD/End-Portal-Creater#3]
The recipe for the portal frame is asking for a diamond instead of the dragons egg. Checking the fabric_item.json file confirms that the requirement has been changed to "minecraft:diamond". I didn't see the change listed anywhere so I am assuming that it was unintentional.

**Comment by PalgamingHD** [comment]
Thats interesting... 
I dont remember this but it's fixed now in the current code
